name: bazar_flutter
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Base Packages
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  # UI Packages
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
