name: bazar_flutter
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Base Packages
  bazar_service_lib:
    path: /Users/kerem/Projects/bazar/bazar_services
    # git:
    #   url: https://github.com/keremkabiloglu/bazar-service-lib.git
    #   ref: main
  cupertino_icons: ^1.0.2
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.1
  # UI Packages
  flutter_staggered_grid_view: ^0.7.0
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: HeyWow
      fonts:
        - asset: assets/fonts/HeyWow/HeyWowBold.ttf
          weight: 700
        - asset: assets/fonts/HeyWow/HeyWowExtraBold.ttf
          weight: 800
        - asset: assets/fonts/HeyWow/HeyWowHeavy.ttf
          weight: 900
        - asset: assets/fonts/HeyWow/HeyWowLight.ttf
          weight: 300
        - asset: assets/fonts/HeyWow/HeyWowMedium.ttf
          weight: 500
        - asset: assets/fonts/HeyWow/HeyWowRegular.ttf
          weight: 400
        - asset: assets/fonts/HeyWow/HeyWowSemiBold.ttf
          weight: 600
