name: bazar_flutter
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Base Packages
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.1
  # UI Packages
  flutter_svg: ^2.0.9
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: HeyWow
      fonts:
        - asset: assets/fonts/HeyWow/HeyWowBold.ttf
          weight: 700
        - asset: assets/fonts/HeyWow/HeyWowExtraBold.ttf
          weight: 800
        - asset: assets/fonts/HeyWow/HeyWowHeavy.ttf
          weight: 900
        - asset: assets/fonts/HeyWow/HeyWowLight.ttf
          weight: 300
        - asset: assets/fonts/HeyWow/HeyWowMedium.ttf
          weight: 500
        - asset: assets/fonts/HeyWow/HeyWowRegular.ttf
          weight: 400
        - asset: assets/fonts/HeyWow/HeyWowSemiBold.ttf
          weight: 600
